# By default, the task type is PICK_ONLY
int8 PICK_ONLY=0
int8 PLACE_ONLY=1
int8 PICK_AND_PLACE=2
int8 task_type

# Planning group properties
string arm_group_name
string hand_group_name

# Robot model and links
string eef_name
string hand_frame

# Object and surfaces
string object_id
string[] support_surfaces

# Picking
# Either provide grasp poses or the name of a grasp_provider_plugin which will generate grasps
moveit_msgs/Grasp grasp                        # If the grasp pose is set, it overrides the grasp provider plugin 
geometry_msgs/PoseStamped[] extra_grasp_poses  # More grasp poses to check (approach and lift direction from the grasp are maintained
geometry_msgs/Pose grasp_frame_transform       # Offsets the eef frame (only set this if necessary) (should we delete it?~felixvd)
string grasp_provider_plugin_name

# Placing
string place_provider_plugin_name
moveit_msgs/PlaceLocation place_location

---

bool success
Solution solution

---

string feedback
